landon:
  guest:
    service.url: http://localhost:8100

spring:
  datasource:
    url: jdbc:h2:mem:landon
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console